//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int ID { get; set; }
        [DisplayName("Username")]
        [Required(ErrorMessage ="Username Required")]
        public string User_Name { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = " Password Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
